"""Stable, independently queued copy for each ParkEz app roundup."""

PARKEZ_ADVICE_SOCIAL_COPY_IDS = [f"parkez-copy-{index:02d}" for index in range(1, 21)]

PARKEZ_ADVICE_SOCIAL_TITLES: dict[str, tuple[str, ...]] = {
    "apps-01": (
        "4 apps para tu día a día con el coche",
        "RadarBot, Waze, Google Maps y ParkEz: cada app para una cosa",
        "Un kit de apps para preparar la ruta y la llegada",
        "Estas cuatro apps merecen un hueco en tu móvil",
        "Avisos, rutas, mapas y aparcamiento en un recopilatorio",
        "Tu próximo viaje empieza con estas apps preparadas",
        "Del primer aviso a buscar sitio con ParkEz",
        "Cuatro herramientas, cuatro partes del trayecto",
        "No todas las apps para el coche hacen lo mismo",
        "Waze para la ruta, ParkEz para pensar dónde aparcar",
        "Qué aporta cada app antes de coger las llaves",
        "El mapa de respaldo también forma parte del kit",
        "Apps útiles para salir con el recorrido pensado",
        "Tu móvil tiene más usos que llevarte al destino",
        "Conoce estas cuatro apps antes de tu próxima salida",
        "La ruta y el aparcamiento necesitan herramientas distintas",
        "Un copiloto digital para preparar el trayecto completo",
        "¿Cuál de estas cuatro aplicaciones te falta por probar?",
        "Prepara las apps antes de ponerte al volante",
        "ParkEz y otras tres apps para organizar tus viajes",
    ),
    "driving-01": (
        "4 apps para dejar tu ruta preparada antes de arrancar",
        "Tus avisos y tu navegador, listos antes de salir",
        "Un recopilatorio de apps para organizar el camino",
        "RadarBot avisa; Waze y Maps te ayudan con la ruta",
        "Apps para el coche que conviene configurar en casa",
        "Cuatro herramientas para preparar un viaje de principio a fin",
        "Elige la ruta y piensa las paradas con estas apps",
        "De los avisos de RadarBot a la búsqueda con ParkEz",
        "Tu siguiente recorrido puede llevar un kit digital",
        "Apps para orientarte sin improvisar al volante",
        "Navegación y avisos: qué hace cada aplicación",
        "Prepara el destino y añade ParkEz a la llegada",
        "Las apps ayudan más cuando las dejas listas a tiempo",
        "Una ruta pensada empieza con cuatro herramientas",
        "Waze y Google Maps: navegación para distintos momentos",
        "Tu checklist de apps antes del próximo trayecto",
        "Cuatro aplicaciones para el camino y el aparcamiento",
        "No esperes a estar conduciendo para preparar el móvil",
        "Avisos de radares, rutas y paradas: este es el kit",
        "Del navegador al sitio donde dejarás el coche",
    ),
    "calm-01": (
        "Apps para preparar la llegada con más calma",
        "Waze avisa de la salida; ParkEz orienta la búsqueda de sitio",
        "Cuatro apps para dejar menos decisiones pendientes",
        "Antes de salir, organiza tu trayecto con estas herramientas",
        "Las apps también pueden ayudarte a planificar el margen",
        "Tu agenda no termina en la hora del navegador",
        "Del destino guardado al aparcamiento: cuatro apps útiles",
        "Prepara el viaje de mañana desde el móvil hoy",
        "Un kit de apps para no dejarlo todo al último minuto",
        "Rutas frecuentes y búsqueda de sitio en el mismo plan",
        "¿Vas con prisa? Conoce estas apps antes de salir",
        "Cuatro herramientas para un trayecto con menos improvisación",
        "Programa la salida y piensa dónde aparcar",
        "Tu próximo compromiso empieza con estas apps preparadas",
        "Navegación, avisos y aparcamiento para organizar la llegada",
        "Las cuatro apps de un viaje pensado con margen",
        "Waze y ParkEz no resuelven la misma parte del viaje",
        "Deja la dirección lista y la búsqueda de sitio orientada",
        "Apps para planificar antes de ponerte al volante",
        "Un recopilatorio para llegar con la ruta y el aparcamiento pensados",
    ),
    "parking-01": (
        "4 apps para llegar, buscar sitio y volver al coche",
        "ParkEz para buscar zona; Google Maps para recordar el coche",
        "Estas apps también son útiles al terminar la ruta",
        "Un kit digital para el camino y el regreso al coche",
        "No cierres el plan cuando el navegador dice que has llegado",
        "Cuatro aplicaciones para preparar el recorrido hasta aparcar",
        "Llegada y aparcamiento: qué aporta cada una de estas apps",
        "Guarda dónde aparcas y prepara por dónde buscar",
        "De Waze a ParkEz: organiza también la última parte",
        "Google Maps tiene un uso después de apagar el motor",
        "Las apps del coche también cuentan para el regreso",
        "Un recopilatorio para preparar destino, zona y vuelta",
        "ParkEz y Google Maps: buscar sitio y guardar la ubicación",
        "Tu móvil puede ayudarte antes y después de aparcar",
        "Cuatro herramientas para no olvidar la llegada en tu plan",
        "El punto de regreso también se guarda con una app",
        "Apps que acompañan el viaje más allá de la dirección",
        "Un recorrido completo con RadarBot, Waze, Maps y ParkEz",
        "Busca aparcamiento con un plan y guarda el coche al llegar",
        "Las cuatro apps de tu próxima salida por la ciudad",
    ),
}

PARKEZ_ADVICE_SOCIAL_INTROS: tuple[str, ...] = (
    "Estas {count_word} apps cubren distintos momentos de tu día a día con el coche.",
    "Cada aplicación tiene su función. Aquí explicamos qué aporta cada una de estas {count_word} herramientas.",
    "Del punto de salida al aparcamiento: conoce estas {count_word} apps antes del próximo trayecto.",
    "Una ruta es más que una dirección. Estas {count_word} aplicaciones también tienen en cuenta la llegada.",
    "Guarda este recopilatorio de {count_word} apps y revísalo con el coche aparcado.",
    "Las apps ayudan más cuando las preparas a tiempo. Estas {count_word} tienen funciones distintas para el viaje.",
    "Tu kit digital para el coche puede empezar con estas {count_word} aplicaciones.",
    "Pensar el viaje antes de arrancar deja menos decisiones pendientes. Conoce estas {count_word} herramientas.",
    "No hace falta elegir una sola app para todo. Así se reparten las tareas estas {count_word} aplicaciones.",
    "Llegar y dejar el coche también forma parte del plan. Mira para qué sirven estas {count_word} apps.",
    "Aquí tienes {count_word} aplicaciones explicadas para preparar tu próxima salida.",
    "Antes de ponerte al volante, descubre qué puede aportar cada una de estas {count_word} apps.",
    "Estas {count_word} aplicaciones reúnen avisos, navegación, planificación y búsqueda de sitio con ParkEz.",
    "Para tu próximo recorrido, deja preparadas las herramientas que necesites de este kit de {count_word} apps.",
    "Un poco de margen empieza con un plan. Estas {count_word} aplicaciones pueden formar parte del tuyo.",
    "El viaje empieza antes de girar la llave. Repasa este recopilatorio de {count_word} apps con el coche aparcado.",
    "No todas resuelven lo mismo: aquí explicamos la utilidad de estas {count_word} aplicaciones para el coche.",
    "Entre salir de casa y volver al coche hay varios pasos. Estas {count_word} herramientas cubren funciones distintas.",
    "Ruta, llegada y búsqueda de sitio: conoce el papel de cada una de estas {count_word} apps.",
    "Comparte este recopilatorio de {count_word} aplicaciones con quien suele organizar sus trayectos desde el móvil.",
)
