"""Stable, independently queued copy for each ParkEz advice pack."""

PARKEZ_ADVICE_SOCIAL_COPY_IDS = [f"parkez-copy-{index:02d}" for index in range(1, 21)]

PARKEZ_ADVICE_SOCIAL_TITLES: dict[str, tuple[str, ...]] = {
    "apps-01": (
        "Tu móvil puede ayudarte antes de arrancar",
        "Waze, Google Maps y ParkEz: cada app para una cosa",
        "La ruta no acaba en el navegador",
        "Prepara estas apps antes de coger las llaves",
        "¿Sin cobertura? Ese mapa se prepara en casa",
        "El kit de apps para salir con el viaje pensado",
        "Llegar, aparcar y volver al coche sin improvisar",
        "Un aviso de salida y un mapa de respaldo",
        "Tres momentos del viaje que puedes preparar con apps",
        "Prepara Waze antes de arrancar",
        "Guarda el mapa y también dónde dejas el coche",
        "De la hora de salida al punto de regreso",
        "Apps útiles para el trayecto y para la llegada",
        "Tu siguiente viaje empieza en los ajustes del móvil",
        "El mapa sin conexión que conviene tener preparado",
        "No necesitas abrir mil apps mientras conduces",
        "Un plan digital para tu día a día con el coche",
        "¿Recuerdas dónde aparcaste? Déjalo guardado",
        "Usa el móvil para preparar, no para distraerte",
        "ParkEz y dos herramientas para planificar el trayecto",
    ),
    "driving-01": (
        "Una salida perdida no merece una maniobra brusca",
        "Conducir con margen empieza antes de salir",
        "Asiento, ruta y música: déjalo listo primero",
        "Pequeños hábitos para no improvisar al volante",
        "El coche de delante necesita su espacio",
        "Tu siguiente trayecto, preparado de principio a fin",
        "Llegar un poco después puede ser la mejor decisión",
        "Antes de arrancar, prepara también la llegada",
        "¿Te pasaste el desvío? Mantén la calma y sigue",
        "Dale espacio a tu conducción",
        "El navegador ayuda; la seguridad manda",
        "Prepara el coche y piensa dónde aparcar",
        "Menos cambios sobre la marcha, más anticipación",
        "Una ruta tranquila no se consigue a base de prisas",
        "No todo se arregla frenando en el último segundo",
        "Haz tu checklist antes de ponerte al volante",
        "Del retrovisor al aparcamiento: piensa el trayecto",
        "Tu móvil puede esperar hasta que estés aparcado",
        "Un desvío, una distancia y un plan para aparcar",
        "Hábitos que merece la pena llevar en cada viaje",
    ),
    "calm-01": (
        "La hora de llegada no incluye siempre aparcar",
        "Planifica la llegada para quitarte una preocupación",
        "Tu plan B también merece un lugar en la ruta",
        "No molestar: un ajuste antes de arrancar",
        "Llegar con margen cambia cómo preparas el viaje",
        "El trayecto termina en la puerta, no en el mapa",
        "No dejes todo el aparcamiento para el último minuto",
        "Una alternativa pensada vale más que otra vuelta",
        "Prepara la ruta sin llenar el móvil de avisos",
        "Aparcar también forma parte de tu agenda",
        "¿Vas con prisa? Piensa antes en la llegada",
        "Más margen y menos cosas que decidir al volante",
        "Haz sitio en tu plan para aparcar y caminar",
        "Tres decisiones antes de salir y un cierre con ParkEz",
        "Las notificaciones no necesitan viajar contigo",
        "Tu próxima cita empieza con un trayecto pensado",
        "No confíes toda la llegada a una plaza en la puerta",
        "Prepara un viaje con menos líos al final",
        "El plan para llegar sin improvisarlo todo",
        "Deja el plan B listo y la búsqueda de sitio orientada",
    ),
    "parking-01": (
        "Una plaza vacía no siempre es una plaza para ti",
        "Aparcar empieza antes de llegar al barrio",
        "No te quedes buscando solo en la misma manzana",
        "Piensa dónde aparcar y cómo volver al coche",
        "Las señales importan más que un hueco libre",
        "Unos minutos a pie también son una opción",
        "Tu búsqueda de aparcamiento necesita un plan B",
        "Antes de alejarte, guarda dónde has aparcado",
        "ParkEz para orientarte; las señales para comprobar",
        "El aparcamiento no termina cuando apagas el motor",
        "Amplía la búsqueda sin improvisar al volante",
        "Destino, sitio y regreso: prepara las tres cosas",
        "¿Todo lleno? Lleva otra zona ya pensada",
        "No confundas hueco libre con estacionamiento permitido",
        "Mira horarios y reservas antes de dejar el coche",
        "El pequeño mapa que necesitas al volver",
        "Otra calle y unos pasos pueden cambiar tu llegada",
        "Guarda la ubicación, no solo el nombre del barrio",
        "Prepara la última parte de tu próximo trayecto",
        "Aparca con un plan, no con vueltas sin rumbo",
    ),
}

PARKEZ_ADVICE_SOCIAL_INTROS: tuple[str, ...] = (
    "Estos {count_word} consejos reúnen preparativos útiles para tu día a día con el coche.",
    "No todo se decide al volante. Aquí tienes {count_word} ideas para dejar más cosas preparadas.",
    "Del punto de salida al aparcamiento: repasa estos {count_word} consejos antes del próximo trayecto.",
    "Una ruta es más que una dirección. Estos {count_word} consejos también tienen en cuenta la llegada.",
    "Si sueles salir sin plan, guarda estas {count_word} ideas para revisarlas con el coche aparcado.",
    "Las apps ayudan más cuando las preparas a tiempo. Estas son {count_word} ideas para tu siguiente viaje.",
    "Tu día a día con el coche puede ir más organizado con estos {count_word} preparativos.",
    "Pensar el viaje antes de arrancar deja menos decisiones pendientes. Empieza por estos {count_word} consejos.",
    "No hace falta resolver todo sobre la marcha. Aquí tienes {count_word} hábitos para preparar el recorrido.",
    "Llegar y dejar el coche también forma parte del plan. Revisa estas {count_word} ideas prácticas.",
    "Guarda este checklist de {count_word} consejos y úsalo cuando prepares tu próxima salida.",
    "Antes de ponerte al volante, dedica un momento a estas {count_word} ideas sobre el trayecto y la llegada.",
    "Estos {count_word} consejos unen planificación, herramientas útiles y una búsqueda de sitio con ParkEz.",
    "Para tu próximo recorrido, prueba estos {count_word} preparativos en lugar de dejarlo todo para el final.",
    "Un poco de margen empieza con un plan. Aquí van {count_word} consejos para organizar tu siguiente trayecto.",
    "El viaje empieza antes de girar la llave. Repasa estos {count_word} consejos con el coche aparcado.",
    "Hay detalles que conviene decidir antes de salir. Estos {count_word} consejos son un buen punto de partida.",
    "Entre salir de casa y volver al coche hay varios pasos. Estas {count_word} ideas te ayudan a pensarlos.",
    "Ruta, llegada y búsqueda de sitio: estos {count_word} consejos ponen el foco en el trayecto completo.",
    "Comparte estas {count_word} ideas con quien siempre termina improvisando al llegar en coche.",
)
